"""GENERATED by ``scripts/gen_research_arms.py`` — do not edit by hand.

The research slot's arms, derived from its arm register
(``arena/research/register.json``, alpha-engine-config-I11442), for
``executor.champion.SHADOW_SERVED_ARMS``. Committed rather than read at
runtime so that no S3 read sits on the trading-start path;
``.github/workflows/research-arms-drift.yml`` fails when the register
carries an arm this tuple does not.

Regenerate with ``python scripts/gen_research_arms.py`` and commit.
"""

RESEARCH_SLOT_ARMS: tuple[str, ...] = (
    "attractiveness_20",
    "attractiveness_60",
    "predictor_from_60",
    "tech_score_20",
    "thinktank_20",
)
